In [2]:
import pandas as pd

In [5]:
df = pd.read_parquet('/workspaces/Bluebikes-trip-mlops/data/2023-07-bluebikes-tripdata.parquet')

In [6]:
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C694F27EDA2FB2A3,docked_bike,2023-07-18 13:48:34,2023-07-18 13:58:44,Roxbury Crossing T Stop - Columbus Ave at Trem...,C32001,Christian Science Plaza - Massachusetts Ave at...,B32005,42.331184,-71.095171,42.343666,-71.085824,member
1,E182C085A7901BD0,docked_bike,2023-07-19 12:16:30,2023-07-19 12:25:23,Roxbury Crossing T Stop - Columbus Ave at Trem...,C32001,Christian Science Plaza - Massachusetts Ave at...,B32005,42.331184,-71.095171,42.343666,-71.085824,member
2,EEAB121638F88C65,docked_bike,2023-07-28 17:49:26,2023-07-28 18:00:08,Roxbury Crossing T Stop - Columbus Ave at Trem...,C32001,Christian Science Plaza - Massachusetts Ave at...,B32005,42.331184,-71.095171,42.343666,-71.085824,member
3,1A1EAD7F0B0D3EC9,docked_bike,2023-07-22 23:14:17,2023-07-22 23:23:32,Roxbury Crossing T Stop - Columbus Ave at Trem...,C32001,Christian Science Plaza - Massachusetts Ave at...,B32005,42.331184,-71.095171,42.343666,-71.085824,member
4,53822DB5B536A35B,docked_bike,2023-07-21 18:41:22,2023-07-21 18:49:00,Roxbury Crossing T Stop - Columbus Ave at Trem...,C32001,Northeastern University - North Parking Lot,B32012,42.331184,-71.095171,42.341814,-71.090179,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
411504,A4742E9801481384,docked_bike,2023-07-05 12:36:57,2023-07-05 12:48:24,Central Sq Post Office / Cambridge City Hall a...,M32012,MIT Carleton St at Amherst St,M32070,42.366426,-71.105495,42.360542,-71.086698,member
411505,364B1DBD9A0F1FCD,docked_bike,2023-07-10 10:58:53,2023-07-10 11:10:38,Central Sq Post Office / Cambridge City Hall a...,M32012,MIT Carleton St at Amherst St,M32070,42.366426,-71.105495,42.360542,-71.086698,member
411506,EE549C7467BC5FEF,docked_bike,2023-07-07 10:13:01,2023-07-07 10:23:15,Central Sq Post Office / Cambridge City Hall a...,M32012,MIT Carleton St at Amherst St,M32070,42.366426,-71.105495,42.360542,-71.086698,member
411507,55D33AD303859E02,docked_bike,2023-07-15 04:16:48,2023-07-22 08:48:30,Swan St. Park,V32007,None,None,42.412505,-71.058422,NaN,NaN,casual
411508,192CFF3DBF7E3388,docked_bike,2023-07-14 21:13:23,2023-07-14 21:26:12,Central Sq Post Office / Cambridge City Hall a...,M32012,MIT Carleton St at Amherst St,M32070,42.366426,-71.105495,42.360542,-71.086698,member

In [3]:
df_2 = pd.read_parquet('/workspaces/Bluebikes-trip-mlops/data/predicted_202307.parquet')

In [4]:
df_2

                 ride_id  predicted_duration
0       C694F27EDA2FB2A3           13.945983
1       E182C085A7901BD0           13.945983
2       EEAB121638F88C65           13.945983
3       1A1EAD7F0B0D3EC9           13.945983
4       53822DB5B536A35B           13.713597
...                  ...                 ...
392145  96AD300A6A44CE6E           13.407084
392146  A4742E9801481384           11.368688
392147  364B1DBD9A0F1FCD           11.368688
392148  EE549C7467BC5FEF           11.368688
392149  192CFF3DBF7E3388           11.368688

[392150 rows x 2 columns]